# Generated by Django 6.0.2 on 2026-02-04 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField()),
                ('job_type', models.CharField(choices=[('PCO', 'PCO'), ('MOT', 'MOT'), ('SERVICE', 'Service')], max_length=20)),
                ('admin_comment', models.TextField(blank=True)),
                ('mechanic_remark', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROCESS', 'In Process'), ('COMPLETED', 'Completed'), ('HOLD', 'Hold')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(limit_choices_to={'userprofile__role': 'MECHANIC'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
