# Generated by Django 6.0.2 on 2026-02-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='appointment',
            field=models.CharField(blank=True, help_text='Car registration / appointment reference', max_length=100, null=True),
        ),
    ]
