# Generated by Django 6.0.2 on 2026-02-05 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_oil_change', models.BooleanField(default=False)),
                ('oil_filter_change', models.BooleanField(default=False)),
                ('cabin_filter', models.BooleanField(default=False)),
                ('air_filter', models.BooleanField(default=False)),
                ('spark_plugs', models.BooleanField(default=False)),
                ('engine_coolant', models.BooleanField(default=False)),
                ('wipers', models.BooleanField(default=False)),
                ('battery', models.BooleanField(default=False)),
                ('brake_pads_front', models.BooleanField(default=False)),
                ('brake_pads_rear', models.BooleanField(default=False)),
                ('tyre_front_right', models.CharField(blank=True, max_length=10)),
                ('tyre_front_left', models.CharField(blank=True, max_length=10)),
                ('tyre_rear_right', models.CharField(blank=True, max_length=10)),
                ('tyre_rear_left', models.CharField(blank=True, max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='jobs.job')),
            ],
        ),
    ]
