# Generated by Django 6.0.2 on 2026-02-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinspection',
            name='antifreeze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='hybrid_filter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='key_bettery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='transmission_oil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='washer_fluid',
            field=models.BooleanField(default=False),
        ),
    ]
