# Generated by Django 6.0.2 on 2026-02-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobinspection_antifreeze_jobinspection_hybrid_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinspection',
            name='accident_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='ball_joint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='break_disc_fr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='break_disc_re',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='h11_bulbs_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='h11_bulbs_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='hid_bulb_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='hid_bulb_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='labour',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='linkage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='navigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='reverse_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='seat_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='shock_absorber_fr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='shock_absorber_re',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='side_bulbs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinspection',
            name='tracking_system',
            field=models.BooleanField(default=False),
        ),
    ]
