# Generated by Django 6.0.2 on 2026-02-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobinspection_accident_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinspection',
            name='tyre_front_left',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobinspection',
            name='tyre_front_right',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobinspection',
            name='tyre_rear_left',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobinspection',
            name='tyre_rear_right',
            field=models.CharField(max_length=10),
        ),
    ]
