# Generated by Django 6.0.2 on 2026-02-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobinspection_tyre_front_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinspection',
            name='labour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobinspection',
            name='tyre_front_left',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobinspection',
            name='tyre_front_right',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobinspection',
            name='tyre_rear_left',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobinspection',
            name='tyre_rear_right',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
